server:
  port: 8089
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aliyun:3306/db0?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Jiansheyin1.
    hikari:
      minimum-idle: 10
      idle-timeout: 180000
      maximum-pool-size: 100
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: aliyun
    port: 6379
    timeout: 10000ms    #连接超时时间（毫秒）
    lettuce:
      pool:
#        max-active: 100   #连接池最大连接数（使用负值表示没有限制）
#        max-wait: 5000ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 50     #连接池中的最大空闲连接
#        min-idle: 5     #连接池中的最小空闲连接
        max-active: 20   #连接池最大连接数（使用负值表示没有限制）
        max-wait: 5000ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10     #连接池中的最大空闲连接
        min-idle: 5     #连接池中的最小空闲连接

      shutdown-timeout: 100ms
    password: Jiansheyin1.
    database: 1

logging:
  level:
    root: info
    com:
      springboot101: debug