
spring:
  redis:
    host: aliyun
    port: 6379
    password: Jiansheyin1.
    database: 0
    lettuce:
      pool:
        min-idle: 10
        max-idle: 100
        max-active: 100
logging:
  level:
    sql: debug
    root: info
server:
  port: 18889
  #        max-wait: 10000