server:
  port: 8089
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aliyun:3306/db0?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Jiansheyin1.
    hikari:
      minimum-idle: 10
      idle-timeout: 180000
      maximum-pool-size: 100
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: aliyun
    port: 6379
    lettuce:
      pool:
        min-idle: 5
        max-active: 10
        max-wait: 1ms
      shutdown-timeout: 100ms
    password: Jiansheyin1.
    database: 0

#
#
#logging:
#  level:
#    root: info
#    com:
#      product: debug